version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinique
      MYSQL_USER: clinique_user
      MYSQL_PASSWORD: clinique_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql-db

  tomcat:
    image: tomcat:10-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/clinique-digital-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/clinique-digital.war
    depends_on:
      - mysql-db

volumes:
  mysql-data: